project:
  type: website
  output-dir: docs

website:
  title: "LASER Institute"
  page-navigation: true
  repo-url: https://github.com/laser-institute/laser-website
  repo-actions: [edit, issue]
  favicon: "images/laser-icon.png"
  
  navbar:
    background: "#427E93"
    logo: "images/laser-icon.png"
    left:
      - href: index.qmd
        text: Home
      - href: curriculum-la.qmd
        text: Curriculum
      - href: instruction-intro.qmd
        text: Instruction
      - href: institute-intro.qmd
        text: Institute
    right:
      - icon: cloud-fill
        href: https://posit.cloud
        aria-label: RStudio Cloud
      - icon: github
        href: https://github.com/laser-institute
  
  sidebar:
    style: "docked"
    search: true
    contents:
    - section: "Curriculum"
      contents:
        - curriculum-la.qmd
        - curriculum-topics.qmd
        - curriculum-activities.qmd
        - curriculum-network-analysis.qmd
    - section: "Instruction"
      contents:
        - instruction-intro.qmd
    - section: "Institute"
      contents:
        - institute-intro.qmd
        - institute-goals.qmd

  page-footer:
      left: "This page is built with [Quarto](https://quarto.org/) and hosted by [GitHub](https://pages.github.com)."
      background: "#427E93"
      right:
      - text: "License"
        href: LICENSE.md
      - text: "Code of Conduct"
        href: CODE_OF_CONDUCT.md  
  
format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, style/dark.scss]
    css: styles.css
    toc: true
    
editor: visual