project:
  type: website
  output-dir: docs

website:
  title: "LASER Institute"
  navbar:
    background: "#427E93"
    logo: "images/laser-icon.png"
    left:
      - href: index.qmd
        text: Home
      - href: modules-overview.qmd
        text: Modules
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/laser-institute
      - icon: cloud-fill
        href: https://posit.cloud
        aria-label: RStudio Cloud
  sidebar:
    style: "docked"
    search: true
    contents:
    - index.qmd
    - section: "Modules"
      contents:
        - modules-overview.qmd
        - modules-network-analysis.qmd
  
  
format:
  html:
    theme: 
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true
    
editor: visual