project:
  type: website

website:
  title: "LASER Institute"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true